- name: Join worker nodes to the cluster
  hosts: all
  any_errors_fatal: true
  tasks:
  - name: read worker join command
    set_fact:
      join_command_local: "{{ lookup('file', 'tmp/{{ cluster_name }}/wrkr_join_command.sh') }}"
    when: "'kube_api_servers' not in group_names and 'kube_etcd_servers' not in group_names"
    tags:
      - kubeadm_join_wrkrs

  - name: join worker nodes to cluster
    command: "{{ join_command_local }}"
    become: true
    when: "'kube_api_servers' not in group_names and 'kube_etcd_servers' not in group_names"
    tags:
      - kubeadm_join_wrkrs