---
- name: Install ingress-nginx on Kubernetes Cluster
  hosts: kube_api_servers[0]
  gather_facts: false
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
    nginx_controller_ip: "{{ cluster_config.nginx_controller_ip }}"
    ingress_nginx_chart_version: "{{ cluster_config.ingress_nginx_chart_version }}"
  tags:
    - install-ingress-nginx

  tasks:
    - name: Add ingress-nginx repository to Helm
      ansible.builtin.shell:
        cmd: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      args:
        executable: /bin/bash

    - name: Update Helm repositories
      ansible.builtin.shell:
        cmd: helm repo update
      args:
        executable: /bin/bash

    - name: Generate ingress-nginx Helm values file
      ansible.builtin.template:
        src: helpers/ingress_nginx_values.yaml.j2
        dest: "/tmp/ingress-nginx-values.yaml"

    - name: Install or upgrade ingress-nginx
      ansible.builtin.shell:
        cmd: >
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
          --version {{ ingress_nginx_chart_version }}
          --create-namespace --namespace ingress-nginx
          --values /tmp/ingress-nginx-values.yaml
      args:
        executable: /bin/bash

    - name: Create ingress-nginx service patch file
      ansible.builtin.copy:
        content: |
          metadata:
            annotations:
              io.cilium/lb-ipam-ips: "{{ nginx_controller_ip }}"
            labels:
              L2Announcement: "true"
        dest: "/tmp/ingress-nginx-svc-patch.yaml"
      tags:
        - patch-ingress-nginx-svc

    - name: Patch ingress-nginx-controller service
      ansible.builtin.shell:
        cmd: |
          kubectl patch -n ingress-nginx svc ingress-nginx-controller --patch-file /tmp/ingress-nginx-svc-patch.yaml
      args:
        executable: /bin/bash
      tags:
        - patch-ingress-nginx-svc