---
- name: Unset Default StorageClass
  hosts: kube_api_servers[0]
  gather_facts: false
  tasks:
    - name: Get all storage classes
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
      register: storage_classes
    - name: Remove default annotation from all storage classes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: "{{ item.metadata.name }}"
            annotations:
              storageclass.kubernetes.io/is-default-class: "false"
      loop: "{{ storage_classes.resources }}"
      when: "'storageclass.kubernetes.io/is-default-class' in item.metadata.annotations and item.metadata.annotations['storageclass.kubernetes.io/is-default-class'] == 'true'"
      loop_control:
        label: "{{ item.metadata.name }}"

- name: Deploy Longhorn on Kubernetes
  hosts: kube_api_servers[0]
  gather_facts: false
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
    longhorn_chart_version: "{{ cluster_config.longhorn.longhorn_chart_version }}"
    longhorn_nfs_storage: "{{ cluster_config.longhorn.longhorn_nfs_storage }}"
    longhorn_domain_name: "{{ cluster_config.longhorn.longhorn_domain_name }}"
    longhorn_tls_secret_name: "{{ cluster_config.longhorn.longhorn_tls_secret_name }}"
    cluster_issuer: "{{ cluster_config.cert_manager.cluster_issuer }}"

  tasks:
    - name: Install ServiceMonitor & PrometheusRule CRDs
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-{{ cluster_config.kube_prometheus_stack.kube_prometheus_stack_version }}/charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
        kubectl apply -f https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-{{ cluster_config.kube_prometheus_stack.kube_prometheus_stack_version }}/charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml

    - name: Calculate the count of non-API/ETCD servers
      set_fact:
        non_api_etcd_server_count: "{{ groups['all'] | length - (groups['kube_api_servers'] | default([]) | length + groups['kube_etcd_servers'] | default([]) | length) }}"

    - name: Determine if needing replicated longhorn volumes based on non-API/ETCD server count
      set_fact:
        longhorn_ephemeral_replica_count: "{{ 1 if non_api_etcd_server_count <= \"1\" else 2 }}"
        longhorn_replica_count: "{{ (non_api_etcd_server_count | int <= 1) | ternary(1, ((non_api_etcd_server_count | int <= 2) | ternary(2, 3))) }}"

    - name: Add Longhorn Helm repository
      ansible.builtin.shell:
        cmd: helm repo add longhorn https://charts.longhorn.io
      args:
        executable: /bin/bash
      tags:
        - install-longhorn

    - name: Update Helm repositories
      ansible.builtin.shell:
        cmd: helm repo update
      args:
        executable: /bin/bash
      tags:
        - install-longhorn

    - name: Generate Longhorn Helm values file
      ansible.builtin.template:
        src: helpers/longhorn_values.yaml.j2
        dest: "/tmp/longhorn-values.yaml"
      tags:
        - install-longhorn

    - name: Install or upgrade Longhorn
      ansible.builtin.shell:
        cmd: >
          helm upgrade --install longhorn longhorn/longhorn
          --namespace longhorn-system
          --create-namespace
          --values /tmp/longhorn-values.yaml
          --version {{ longhorn_chart_version }}
      args:
        executable: /bin/bash
      tags:
        - install-longhorn

    - name: Generate Longhorn ephemeral StorageClass from template
      ansible.builtin.template:
        src: helpers/longhorn_ephemeral_storageclass.yaml.j2
        dest: "/tmp/longhorn-ephemeral-storageclass.yaml"
      tags:
        - longhorn-emphemeral-storageclass

    - name: Create Longhorn ephemeral StorageClass
      ansible.builtin.command:
        cmd: kubectl apply -f /tmp/longhorn-ephemeral-storageclass.yaml
      tags:
        - longhorn-emphemeral-storageclass

- name: Add ingress for Longhorn UI
  hosts: kube_api_servers[0]
  gather_facts: false
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
    ingress_definitions:
      - name: longhorn-ingress
        namespace: longhorn-system
        hostname: "{{ cluster_config.longhorn.longhorn_domain_name }}"
        service_name: "longhorn-frontend"
        service_port: 80
        tls_secret_name: "{{ cluster_config.longhorn.longhorn_tls_secret_name }}"
        cluster_issuer: "{{ cluster_config.cert_manager.cluster_issuer }}"
        ingress_class: "nginx-local"
        upstream_tls: false
        basic_auth: true

  tasks:
    - name: Generate htpasswd file
      ansible.builtin.command:
        cmd: "htpasswd -cb auth {{ ingress_basic_auth_username }} {{ ingress_basic_auth_password }}"
        creates: auth
      tags:
        - add_basic_auth_secret
    - name: Create Kubernetes secret for basic auth
      ansible.builtin.shell: |
        kubectl delete secret basic-auth -n longhorn-system --ignore-not-found
        kubectl create secret generic basic-auth --from-file=auth -n longhorn-system
      tags:
        - add_basic_auth_secret
    - name: Clean up temporary htpasswd file
      ansible.builtin.file:
        path: auth
        state: absent
      tags:
        - add_basic_auth_secret

    - name: Generate Longhorn ui ingress manifests from template
      ansible.builtin.template:
        src: helpers/ingress_template.yaml.j2
        dest: "/tmp/longhorn_ingress.yaml"
      tags:
        - add_ingress
    - name: Apply Longhorn ui ingress manifest
      ansible.builtin.command:
        cmd: kubectl apply -f /tmp/longhorn_ingress.yaml
      tags:
        - add_ingress

- name: Deploy Grafana Dashboard
  hosts: kube_api_servers[0]
  gather_facts: no
  tags:
    - deploy-grafana-dashboard
  vars:
    dashboards:
      - configmap_name: longhorn-overview-dashboard
        url: https://grafana.com/api/dashboards/16888/revisions/8/download
        dashboard_name: "Longhorn / Overview"
  tasks:
    - name: Deploy dashboard to longhorn-system
      include_tasks: helpers/ansible_import_dashboard.yaml
      vars:
        dashboard_url: "{{ item.url }}"
        configmap_name: "{{ item.configmap_name }}"
        dashboard_name: "{{ item.dashboard_name }}"
        namespace: longhorn-system
      loop: "{{ dashboards }}"