- name: Untaint control plane if no worker nodes will be added
  hosts: kube_api_servers[0]
  gather_facts: false
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
  tags:
    - untaint_control_plane
  tasks:
    - name: Calculate quantity of non-API/ETCD nodes
      set_fact:
        non_api_etcd_node_count: "{{ groups['all'] | difference(groups['kube_api_servers'] | default([])) | difference(groups['kube_etcd_servers'] | default([])) | length }}"
    - name: Check for master NoSchedule taints on nodes
      ansible.builtin.command: kubectl get nodes -o json
      register: nodes_json
      when: non_api_etcd_node_count == "0"
    - name: Set fact for nodes with master NoSchedule taint
      set_fact:
        master_taint_nodes: "{{ nodes_json.stdout | from_json | json_query(query) }}"
      vars:
        query: "items[?spec.taints[?key=='node-role.kubernetes.io/master' && effect=='NoSchedule']].metadata.name"
      when: non_api_etcd_node_count == "0"
    - name: Untaint nodes with master NoSchedule taint
      ansible.builtin.command: kubectl taint nodes {{ item }} node-role.kubernetes.io/master:NoSchedule-
      loop: "{{ master_taint_nodes }}"
      when:
        - non_api_etcd_node_count == "0"
        - master_taint_nodes | default([]) | length > 0
      ignore_errors: yes
    - name: Set fact for nodes with control-plane NoSchedule taint
      set_fact:
        control_plane_taint_nodes: "{{ nodes_json.stdout | from_json | json_query(query) }}"
      vars:
        query: "items[?spec.taints[?key=='node-role.kubernetes.io/control-plane' && effect=='NoSchedule']].metadata.name"
      when: non_api_etcd_node_count == "0"
    - name: Untaint nodes with control-plane NoSchedule taint
      ansible.builtin.command: kubectl taint nodes {{ item }} node-role.kubernetes.io/control-plane:NoSchedule-
      loop: "{{ control_plane_taint_nodes }}"
      when:
        - non_api_etcd_node_count == "0"
        - control_plane_taint_nodes | default([]) | length > 0
      ignore_errors: yes