---
- name: Configure and Install Cert-Manager with Helm and Cloudflare DNS01 Solver
  hosts: kube_api_servers[0]
  gather_facts: no
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
  tasks:
    - name: Generate cert-manager configuration from template
      ansible.builtin.template:
        src: "helpers/cert_manager.yaml.j2"
        dest: "/tmp/cert-manager.yaml"

    - name: Generate ClusterIssuers configuration from template
      ansible.builtin.template:
        src: "helpers/clusterissuers.yaml.j2"
        dest: "/tmp/clusterissuers.yaml"

    - name: Generate Cloudflare secret configuration from template
      ansible.builtin.template:
        src: "helpers/secret_cloudflare.yaml.j2"
        dest: "/tmp/secret-cloudflare.yaml"

    - name: Add Jetstack Helm repository and update
      ansible.builtin.shell:
        cmd: "helm repo add jetstack https://charts.jetstack.io && helm repo update"

    - name: Install cert-manager via Helm
      ansible.builtin.command:
        cmd: >
          helm upgrade --install cert-manager jetstack/cert-manager
          --namespace cert-manager --create-namespace
          --version "{{ cluster_config.cert_manager_chart_version }}"
          -f /tmp/cert-manager.yaml

    - name: Apply ClusterIssuers and Secret configuration
      ansible.builtin.shell:
        cmd: kubectl apply -f /tmp/clusterissuers.yaml -f /tmp/secret-cloudflare.yaml -n cert-manager

    - name: Remove configuration files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/secret-cloudflare.yaml"
        - "/tmp/clusterissuers.yaml"
        - "/tmp/cert-manager.yaml"

# This dashboard doesn't seem to work with this version of cert-manager
#- name: Deploy Grafana Dashboard
#  hosts: kube_api_servers[0]
#  gather_facts: no
#  tags:
#    - deploy-grafana-dashboard
#  vars:
#    dashboards:
#      - configmap_name: cert-manager-overview-dashboard
#        url: https://grafana.com/api/dashboards/20340/revisions/1/download
#        dashboard_name: "Cert-Manager / Overview"
#  tasks:
#    - name: Deploy dashboard to cert-manager namespace
#      include_tasks: helpers/ansible_import_dashboard.yaml
#      vars:
#        dashboard_url: "{{ item.url }}"
#        configmap_name: "{{ item.configmap_name }}"
#        dashboard_name: "{{ item.dashboard_name }}"
#        namespace: cert-manager
#      loop: "{{ dashboards }}"