---
- name: Join other control plane nodes to the cluster
  hosts: kube_api_servers[1:]
  any_errors_fatal: true
  tasks:
  - name: read control plane join command
    set_fact:
      join_command_local: "{{ lookup('file', 'tmp/cp_join_command.sh') }}"
    tags:
      - kubeadm_join_cps

  - name: join control plane agents to cluster
    command: "{{ join_command_local }}"
    become: true
    tags:
      - kubeadm_join_cps

- name: Join worker nodes to the cluster
  hosts: all
  any_errors_fatal: true
  tasks:
  - name: read worker join command
    set_fact:
      join_command_local: "{{ lookup('file', 'tmp/wrkr_join_command.sh') }}"
    when: "'kube_api_servers' not in group_names and 'kube_etcd_servers' not in group_names"
    tags:
      - kubeadm_join_wrkrs

  - name: join worker agents to cluster
    command: "{{ join_command_local }}"
    become: true
    when: "'kube_api_servers' not in group_names and 'kube_etcd_servers' not in group_names"
    tags:
      - kubeadm_join_wrkrs