---
- name: Reset Kubernetes Cluster
  hosts: all
  become: true
  vars:
    cluster_config: "{{ lookup('file', 'tmp/cluster_config.json') | from_json }}"
  tasks:
    - name: Stop kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: stopped
        enabled: no

    - name: Stop and delete all containerd containers
      ansible.builtin.script: helpers/delete_containerd_containers.sh
      args:
        executable: /bin/bash

    - name: Stop container runtime service (containerd used as an example)
      ansible.builtin.systemd:
        name: containerd
        state: stopped
        enabled: no

    - name: Run kubeadm reset
      ansible.builtin.command:
        cmd: kubeadm reset -f
      ignore_errors: yes

    - name: Flush iptables rules
      ansible.builtin.iptables:
        flush: yes

    - name: Delete all iptables chains
      ansible.builtin.shell: iptables -X
      ignore_errors: yes

    - name: Clear IPVS tables
      ansible.builtin.shell: ipvsadm --clear
      ignore_errors: yes

    - name: Remove Kubernetes configuration directory
      ansible.builtin.file:
        path: /etc/kubernetes/
        state: absent

    - name: Delete manifests and pki files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ cluster_config.ssh_home }}/.kube/"
        - "{{ cluster_config.ssh_home }}/kubeadm-config.yaml"
        - "{{ cluster_config.ssh_home }}/kubeadmcfg.yaml"