---
# Playbook to install various tools and components
# Mirrors sections of source-packages.sh that consume a version number
- name: Reinstall various tools and components
  hosts: all
  gather_facts: false
  become: true
  vars:
    arch: "amd64"

  tasks:
    # Reinstall and configure CNI plugins
    - name: Ensure /opt/cni/bin directory exists
      ansible.builtin.file:
        path: /opt/cni/bin
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Clean up existing CNI plugins in /opt/cni/bin
      ansible.builtin.file:
        path: /opt/cni/bin
        state: absent
      ignore_errors: true
    - name: Re-create /opt/cni/bin directory
      ansible.builtin.file:
        path: /opt/cni/bin
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: Download CNI plugins
      ansible.builtin.get_url:
        url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-{{ arch }}-v{{ cni_plugins_version }}.tgz"
        dest: "/tmp/cni-plugins-linux-{{ arch }}-v{{ cni_plugins_version }}.tgz"
    - name: Extract CNI plugins
      ansible.builtin.unarchive:
        src: "/tmp/cni-plugins-linux-{{ arch }}-v{{ cni_plugins_version }}.tgz"
        dest: "/opt/cni/bin"
        remote_src: yes
        owner: root
        group: root
        mode: '0755'
    - name: Clean up CNI plugin archive
      ansible.builtin.file:
        path: "/tmp/cni-plugins-linux-{{ arch }}-v{{ cni_plugins_version }}.tgz"
        state: absent

    # Reinstall Cilium CLI
    - name: Reinstall Cilium CLI
      ansible.builtin.shell: |
        curl -s -L --remote-name-all "https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_cli_version }}/cilium-linux-{{ arch }}.tar.gz{,.sha256sum}"
        sha256sum --check cilium-linux-{{ arch }}.tar.gz.sha256sum
        tar -xzf cilium-linux-{{ arch }}.tar.gz -C /usr/local/bin
        rm -f cilium-linux-{{ arch }}.tar.gz*
